### ISSUE TITLE
Font Compile Issue with Combining Grapheme Joiner 

### ISSUE THREAD

**Issue by dyacob** [silnrsi/font-abyssinica#9]
When I build Abyssinica-SIL with `fontmake` as per:

```
fontmake -u AbyssinicaSIL-Regular.ufo -o ttf
```
the info message will appear:

```
INFO:ufo2ft.featureWriters.markFeatureWriter.MarkFeatureWriter:The base glyph uni02D0 and mark glyph uni034F are ambiguously connected by several anchor classes: MC_L, MC_U. The last one will prevail
```

Looking into the glyphs mentioned, I see that `U+02D0` (Modifier Letter Triangular Colon) has both `U` and `L` anchors.  `U+034F` in turn has both `_U` and `_L` positioning marks (one on top of the other). There are no other glyphs with `L` or `_L`.

I see how this becomes ambiguous, I'm not familiar with either `U+02D0` or `U+034F` but comparing with Doulos SIL, `U+034F` had only one position mark labeled `_none`.  The output with `fontmake` then does not appear.

My suggestion would be to mirror the Doulos SIL approach, replacing `_L` & `_U` with `_none` and adding U+034F to the `_none` markClass (which may be automatic with the replacement).  I'm available to make this change and submit a PR if this appears to be the right thing to do.

**Comment by LornaSIL** [comment]
Did this.
